// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkuwwgercajnksdzorij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprdXd3Z2VyY2FqbmtzZHpvcmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTQyMTMsImV4cCI6MjA2Mzc3MDIxM30.OLZZrN42-H02-2r6mUXn5LU1Caove0PogM1yOgJu_C4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);